### PR TITLE
Fix DEL behaves wrongly on blank lines

### PR DESCRIPTION
**Pull request by kofifus**
Fix for https://github.com/firebase/firepad/issues/209

### CODE REVIEW

**Comment by mikagenic** [comment]
I signed it!

**Comment by mikagenic** [comment]
Pull request here

https://github.com/firebase/firepad/commit/cbbcfc257ae506f7f6543e694beab902ac6be3c5

**Comment by mikagenic** [comment]
I signed it!

**Comment by mikelehen** [comment]
I tweaked this and committed it as https://github.com/firebase/firepad/commit/cc458e487a7e47aa01832066bc3f2291f4b16805

**Pull request closed without merging**
