### PR TITLE
fix set html inserts extra new line at the end

### PR DESCRIPTION
**Pull request by mikagenic**
insertHtmlAtCursor etc inserts a newline (\n) after every line including the last line. The newline after the last line should not be there.

This becomes important when trying to implement a paste html functionality using insertHtmlAtCursor  instead of the default CM paste. Pasting (inserting html) inside a line gets broken because you get an extra linebreak at the end that pushes the next letter to a new line.

This pull request changes firepad.textPiecesToInserts to not insert a newline after the last line. Also included is an updated examples\firepad.js so that this fix can be linked to from jsfiddle etc.

### CODE REVIEW

**Comment by mikelehen** [comment]
Cool, thanks.  Can you add a test for this?  (there are a bunch of parse html tests already)

**Comment by mikagenic** [comment]
I'm not sure exactly where the tests are, can you send a link to a relevant
one pls ?

**Comment by mikelehen** [comment]
You can open test/index.html in a browser to see them run (make sure you've run "bower install" and "npm install").

The tests I was thinking of are https://github.com/firebase/firepad/blob/master/test/specs/parse-html.spec.js but it looks like they only test the parsing, not how it's inserted into the text. :-/  So it's probably not quite straightforward.  So nevermind. I'll go ahead and merge.

**Comment by mikagenic** [comment]
great thank you !

**Pull request merged**
