### PR TITLE
Ace v1.2.0 support

### PR DESCRIPTION
**Pull request by 1j01**

### CODE REVIEW

**Comment by mikelehen** [comment]
Looks good.  Thanks!

**Comment by itjustwerks** [comment]
Is this fix part of what we get from the latest "bower install firebase" command (v1.2.0)? I am trying to use the latest version of ACE in an Angular app and every keystroke is logging this "Cannot read property 'action' of undefined" error, plus the behavior is bizarre and nothing is saving to Firebase. Do I need to clone this repo and build it myself to get the fix? Thanks.

**Comment by mikelehen** [comment]
Sorry.  It looks like I haven't released this yet.  You'll have to clone
from github to get the fix for now.  I'll see if I can push a new release
next week.

-Michael

**Comment by itjustwerks** [comment]
All good. I did find it and updated my local version and it works perfectly. Thank you!

**Pull request merged**
