### PR TITLE
Exclude jsdom from browserify builds

### PR DESCRIPTION
**Pull request by rstacruz**
This fixes compatibility with browserify: #231.

### CODE REVIEW

**Comment by rstacruz** [comment]
Here's another project that uses the same convention:

https://github.com/socketio/engine.io-client/blob/master/package.json#L56

**Comment by mikelehen** [comment]
Thanks!  Looks good, merging!

**Comment by rstacruz** [comment]
hmm, an even better fix would probably be to exclude firepad.Headless from the browser build.

https://github.com/firebase/firepad/blob/f618700f9467d067e84bb2e5a11ddd4c6ad2c2a2/lib/headless.js

**Comment by cben** [comment]
I'm not currently using browserify but I have a use for Headless in the
browser.
11 февр. 2016 г. 7:13 пользователь "Rico Sta. Cruz" <
notifications@github.com> написал:

**Pull request merged**
